# -*- coding: utf-8 -*-
"""AR-Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xh2Vjj4u5zpAv97ssE6UpFKDDCUhz72Y
"""

# install tensorflow
!pip install -q tensorflow==2.0.0-beta1
import tensorflow as tf

# check tensorflow version
print(tf.__version__)

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Upload a python file with some useful functions
from google.colab import files
uploaded = files.upload()

from ARHelperFunctions import *

series = CreateSeries(length=200, random_noise=0.1)

# plot noisy series
plt.plot(series)
plt.show()

X_train, Y_train, X_test, Y_test = BuildDataset(series, num_lags=10)

model = ModelBuild(T=10)

model.compile(loss="mse", optimizer=Adam(lr=0.1))

training_logs = model.fit(X_train, Y_train, 
                          epochs=30, validation_data=(X_test, Y_test),
                          verbose=0)

plt.plot(training_logs.history["loss"], label="loss")
plt.plot(training_logs.history["val_loss"], label="val_loss")
plt.legend()